osx_image: xcode8.3
language: objective-c

before_install:
  - gem install xcpretty
  - carthage version
  - carthage bootstrap --platform iOS

script:
  - xcodebuild build -scheme ParkenDD

notifications:
  email:
    on_success: never
